package org.iadb.iic.apps.factcuid.controller;

/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
import io.swagger.annotations.*;

import javax.validation.Valid;

import org.iadb.iic.apps.factcuid.model.Project;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-10-05T07:05:17.201Z[GMT]")
@Api(value = "project", description = "the project API")
public interface ProjectApi {

    @ApiOperation(value = "GetProject", nickname = "getProject", notes = "Get Project details", response = Project.class, authorizations = {
        @Authorization(value = "apiKeyHeader"),
@Authorization(value = "apiKeyQuery")    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Project details", response = Project.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/project/{projId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Project> getProject(@ApiParam(value = "Fact Project Id",required=true) @PathVariable("projId") Integer projId
);


    @ApiOperation(value = "PostProject", nickname = "postproject", notes = "Create Project", authorizations = {
        @Authorization(value = "apiKeyHeader"),
@Authorization(value = "apiKeyQuery")    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 409, message = "Conflict") })
    @RequestMapping(value = "/project",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> postproject(@ApiParam(value = "Project Details"  )  @Valid @RequestBody Project body);

}


